my/urls.py
from django.contrib import admin
from django.urls import include , path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailedView.as_view(),name='detailed'),
    path('<int:pk>/results/',views.Result.as_view(),name='results'),
    path('<int:question_id>/votes/',views.votes,name='votes'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    puplished_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_puplished_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.puplished_date <= now
    was_puplished_recently.admin_order_field = 'puplished_date'
    was_puplished_recently.boolean = True
    was_puplished_recently.short_description = ' puplished recently ?'


class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote_tally = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from polls.models import Questions, Choice
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone


# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        return Questions.objects.filter(
                puplished_date__lte=timezone.now()
                ).order_by('puplished_date')[0:5]


class DetailedView(generic.DetailView):
    model = Questions
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Questions.objects.filter(puplished_date__lte=timezone.now())


class Result(generic.DetailView):
    model = Questions
    template_name = 'polls/results.html'


def votes(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, ' polls/detail.html', {
           'question': question,
           'error_message': " you didn't select a choice ",
        })

    else:
        selected_choice.vote_tally += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
   <h1> {{ object.question_text }} </h1>

   {% if error_message %} <p> <strong> {{ error_message }} </strong> </p> {% endif %}

   <form  action="{% url 'polls:votes' object.pk %}" method="post">

       {% csrf_token %}
       {% for choice in object.choice_set.all %}
           <input type="radio" name='choice' id="choice{{ forloop.counter}} " value="{{ choice.id }}">
           <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label>
       <br>
       {% endfor %}

       <input type="submit" value="Vote">
   </form>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> The polls </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>

{% if latest_questions %}

<ul>
    {% for q in latest_questions %}
    <li>
        <a href="{% url 'polls:detailed' q.id %}">{{ q.question_text }}</a>
    </li>
    </br>
    {% endfor %}
</ul>

{% else %}
     <p> No polls are available. </p>
{% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>results</title>
</head>
<body>
   <h1> you see the result of the question {{ object.question_text }}</h1>
   <ul>
       {% for choice in object.choice_set.all %}
            <li>
                {{ choice.choice_text }} {{ choice.vote_tally }}  vote{{vote.vote_tally|pluralize}}
            </li>
       {%endfor%}
   </ul>

<a href="{% url 'polls:detailed' object.pk %}"> vote again ? </a>
</body>
</html>